{
 "title": "Payments Health Dashboard - Live",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "paymentProvider",
    "label": "Payment Provider",
    "query": "Square : SQUARE, Stripe : STRIPE, Cash : CASH, LawPay : LAWPAY, PayPal : PAYPAL"
   },
   {
    "name": "currency",
    "label": "Currency",
    "query": {}
   },
   { "name": "anywhereAccountId", "label": "Anywhere Account ID" }
  ]
 },
 "panels": [
  { "title": "Payment Capture Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Payment Capture Stats",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  COUNT(*) AS `Total Captures`,\n\n  -- Successful capture count\n  SUM(CASE WHEN JSON_VALUE(labels.event_name) = 'payment_captured' THEN 1 ELSE 0 END) AS `Successful Captures`,\n\n  -- Failed capture count (includes multiple failure events)\n  SUM(CASE WHEN JSON_VALUE(labels.event_name) IN ('payment_capture_failed', 'payment_captured.error') THEN 1 ELSE 0 END) AS `Failed Captures`,\n\n  -- Failed capture percentage\n  (SUM(CASE WHEN JSON_VALUE(labels.event_name) IN ('payment_capture_failed', 'payment_captured.error') THEN 1 ELSE 0 END) * 100.0) / COUNT(*) AS `Failed Captures %`,\n\n  -- Successful capture percentage\n  (SUM(CASE WHEN JSON_VALUE(labels.event_name) = 'payment_captured' THEN 1 ELSE 0 END) * 100.0) / COUNT(*) AS `Successful Captures %`\n\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  $__timeFilter(timestamp)\n  AND JSON_VALUE(json_payload.paymentProvider) IN ($paymentProvider)\n  AND JSON_VALUE(labels.event_name) IN (\n    'payment_captured',\n    'payment_capture_failed',\n    'payment_captured.error'\n  )\n  AND (\n  '$anywhereAccountId' = ''\n  OR json_value(json_payload.customerKey) = '$anywhereAccountId'\n  );\n"
    }
   ]
  },
  {
   "title": "Payment Capture failed Stats in %",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  JSON_VALUE(json_payload.paymentProvider) AS `Payment Provider`,\n\n  -- Failed capture percentage\n  (SUM(CASE WHEN JSON_VALUE(labels.event_name) IN ('payment_capture_failed', 'payment_captured.error') THEN 1 ELSE 0 END) * 100.0) / COUNT(*) AS `Failed Captures %`\n\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  $__timeFilter(timestamp)\n  AND JSON_VALUE(json_payload.paymentProvider) IN ($paymentProvider)\n  AND JSON_VALUE(labels.event_name) IN (\n    'payment_captured',\n    'payment_capture_failed',\n    'payment_captured.error'\n  )\n  AND (\n  '$anywhereAccountId' = ''\n  OR json_value(json_payload.customerKey) = '$anywhereAccountId'\n  )\nGROUP BY\n  JSON_VALUE(json_payload.paymentProvider)\n"
    }
   ]
  },
  { "title": "Total Payment Captures per PSP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Payments capture Success",
   "type": "table",
   "description": "The total number of Successful payments captures.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n    -- Total capture count (successful + failed captures)\n  COUNT(*) AS `Total Capture Count`,\n  \n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  \n  -- Successful capture count\n  SUM(CASE WHEN json_value(labels.event_name) = 'payment_captured' THEN 1 ELSE 0 END) AS `Successful Capture Count`,\n\n  -- Failed capture count (includes multiple failure events)\n  SUM(CASE WHEN json_value(labels.event_name) IN ('payment_capture_failed', 'payment_captured.error') THEN 1 ELSE 0 END) AS `Failed Capture Count`\n\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) IN ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\n  AND json_value(labels.event_name) IN ('payment_captured', 'payment_capture_failed', 'payment_captured.error')\nGROUP BY\n  paymentProvider"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Errors (latest 1000)",
   "type": "table",
   "description": "Details of errors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  JSON_VALUE(json_payload.customerKey) `Anywhere Account ID`,\n  JSON_VALUE(json_payload.paymentProvider) `Payment Provider`,\n  timestamp,\n  JSON_VALUE(json_payload.totalAmount.currency) `Currency`,\n  JSON_VALUE(json_payload.totalAmount.amount) `Amount`,\n  TO_JSON_STRING(json_payload) `Error Details`,\n  trace `Trace Id`\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  severity = 'ERROR'\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\n  AND (\n  '$anywhereAccountId' = ''\n  OR json_value(json_payload.customerKey) = '$anywhereAccountId'\n  )\nORDER BY\n  timestamp asc\nLIMIT 1000"
    }
   ]
  },
  { "title": "Payment Capture Failure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Capture failures",
   "type": "table",
   "description": "Details of capture failures",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  timestamp,\n  json_value(json_payload.paymentProvider) `Payment Provider`,\n  JSON_VALUE(json_payload.customerKey) `Anywhere Account id`,\n  TO_JSON_STRING(json_payload.error) `Error Details`\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('payment_capture_failed' , 'payment_captured.error'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\n  AND (\n  '$anywhereAccountId' = ''\n  OR json_value(json_payload.customerKey) = '$anywhereAccountId'\n  )\nORDER BY\n  timestamp desc,\n  `Payment Provider`\n  "
    }
   ]
  },
  {
   "title": "Payments capture failed",
   "type": "timeseries",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Capture Fail Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('payment_capture_failed' , 'payment_captured.error'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  time asc"
    }
   ]
  },
  {
   "title": "Payments capture failed",
   "type": "table",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Capture Fail Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('payment_capture_failed' , 'payment_captured.error'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  paymentProvider,\n  time desc"
    }
   ]
  },
  { "title": "Payment Checkout Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Payment Checkout failures",
   "type": "table",
   "description": "Details of Authorize failures",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  timestamp,\n  json_value(json_payload.paymentProvider) `Payment Provider`,\n  JSON_VALUE(json_payload.customerKey) `Anywhere Account id`,\n  TO_JSON_STRING(json_payload.error) `Error Details`\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('checkout.error'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\n  AND (\n  '$anywhereAccountId' = ''\n  OR json_value(json_payload.customerKey) = '$anywhereAccountId'\n  )\nORDER BY\n  timestamp desc,\n  `Payment Provider`\n  "
    }
   ]
  },
  {
   "title": "Payment Checkout failures",
   "type": "timeseries",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Authorise Fail Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('checkout.error'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  paymentProvider,\n  time"
    }
   ]
  },
  {
   "title": "Payments Checkout Failures",
   "type": "table",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Authorise Fail Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('checkout.error'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  paymentProvider,\n  time"
    }
   ]
  },
  { "title": "Payment Capture Success", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Payments capture Success",
   "type": "timeseries",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Capture Success Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('payment_captured'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  time asc"
    }
   ]
  },
  {
   "title": "Payments capture failed",
   "type": "table",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Capture Success Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('payment_captured'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  paymentProvider,\n  time desc"
    }
   ]
  },
  { "title": "Checkout Success", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Checkout Success",
   "type": "timeseries",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Checkout Success Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('checkout'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  time asc"
    }
   ]
  },
  {
   "title": "Checkout Success",
   "type": "table",
   "description": "The total number of failed payments captures. This occurs for multiple reasons, e.g. invalid credit card data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "location": "US",
     "project": "anywhere-cloudops-production",
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  json_value(json_payload.paymentProvider) AS paymentProvider,\n  count(*) AS `Checkout Success Count`,\nFROM\n  `adaptive-payments.events._AllLogs`\nWHERE\n  (json_value(labels.event_name) in ('checkout'))\n  AND $__timeFilter(timestamp)\n  AND json_value(json_payload.paymentProvider) IN ($paymentProvider)\n  AND (json_value(json_payload.totalAmount.currency) in ($currency) OR json_value(json_payload.totalAmount.currency) IS NULL)\nGROUP BY\n  paymentProvider,\n  time\nORDER BY\n  paymentProvider,\n  time desc"
    }
   ]
  }
 ]
}